# Generated by Django 4.1.13 on 2024-10-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notifications',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
