# Generated by Django 4.1.13 on 2024-10-22 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essay', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvement_score', models.IntegerField(default=0)),
                ('graph_image', models.CharField(blank=True, max_length=500)),
                ('comparison_data', models.TextField(blank=True)),
                ('progress_date', models.DateTimeField(auto_now_add=True)),
                ('essay_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_essay', to='essay.essay')),
                ('essay_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_essay', to='essay.essay')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_essay_feedback', models.TextField()),
                ('inter_essay_feedback', models.TextField()),
                ('keywords', models.TextField()),
                ('intro_keywords', models.TextField()),
                ('mid_keywords', models.TextField()),
                ('intro_mid_keywords', models.TextField()),
                ('intro_conclusion_keywords', models.TextField()),
                ('mid_conclusion_keywords', models.TextField()),
                ('wordcloud_image', models.CharField(blank=True, max_length=500)),
                ('venn_diagram_image', models.CharField(blank=True, max_length=500)),
                ('radar_wheel_image', models.CharField(blank=True, max_length=500)),
                ('keyword_graph_html', models.TextField(blank=True)),
                ('coherence_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('teacher_feedback', models.TextField(blank=True, null=True)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='essay.essay')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
