# Generated by Django 4.1.13 on 2024-10-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='keyword_score',
        ),
        migrations.AddField(
            model_name='feedback',
            name='grammar_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='keyword_usage_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='originality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='structure_score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
