# Generated by Django 4.1.13 on 2024-10-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_keyword_score_feedback_grammar_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='grammar_score',
            new_name='depth_of_analysis_score',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='keyword_usage_score',
            new_name='keyword_density_score',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='structure_score',
            new_name='topic_relevance_score',
        ),
    ]
