# Generated by Django 4.1.13 on 2024-10-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0003_initial'),
        ('feedback', '0003_rename_grammar_score_feedback_depth_of_analysis_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='essay.assignment'),
            preserve_default=False,
        ),
    ]
