# Generated by Django 4.1.13 on 2024-10-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='assignment',
        ),
    ]
