# Generated by Django 4.1.13 on 2024-10-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0003_initial'),
        ('feedback', '0005_remove_feedback_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_feedback', to='essay.assignment'),
        ),
    ]
