# Generated by Django 5.1.3 on 2025-01-21 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0003_initial'),
        ('feedback', '0006_feedback_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='mid_keywords',
        ),
        migrations.AddField(
            model_name='feedback',
            name='conclusion_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='feedback',
            name='intro_mid_conclusion_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='feedback',
            name='middle_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='intro_conclusion_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='intro_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='intro_mid_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mid_conclusion_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_image', models.CharField(max_length=500)),
                ('compared_feedback', models.TextField(max_length=500)),
                ('progress_date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_progress', to='essay.assignment')),
                ('essay_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_essay', to='essay.essay')),
                ('essay_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_essay', to='essay.essay')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
